#!/bin/bash

if [[ "$#" > 0 ]]; then
  HUBFLOW="$1"; shift
else
  : ${HUBFLOW:="$(unset CDPATH; cd -P -- "$(dirname -- "${BASH_SOURCE}")/.." && pwd -P)"}
fi

export HUBFLOW

PATH="$HUBFLOW/bin:$PATH"
hash -r

if [[ -z "${GIT_SSH:-}" ]]; then
  export GIT_SSH="$HUBFLOW/libexec/ssh-wrapper"
fi

ghome="$(unset CDPATH; cd -P -- "./$(git rev-parse --show-cdup)" && pwd -P)"

function gut {
  echo "> git" "$@" 1>&2
  exec $(type -P git) "$@"
}
