#!/bin/bash

#/ NAME
#/     git hub -- GitHub specific commands
#/
#/ SYNOPSIS
#/     git hub <sub-command>

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"

# load a meat library
source "$shome/libexec/_treadstone"

# entry point
function main {
  hub "$@"
}

require sub "$BASH_SOURCE" "$@"
