#!/bin/bash

#/ NAME
#/     jason -- uses the jason bourne lib
#/
#/ SYNOPSIS
#/     jason

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require paul

# entry point
function main {
  $shome/libexec/gh "$@"
}

require 'sub' "$BASH_SOURCE" "$@"
