#!/bin/bash

#/ NAME
#/     filter -- runs a git filter, as in https://gist.github.com/3430823
#/
#/ SYNOPSIS
#/     filter type stage secrets

# figure out the project root under which bin, lib live
shome="$(cd -P -- "$(dirname -- "$0")/.." && pwd -P)"

# load a meat library
source "$shome/libexec_jason"

# entry point
function main {
  local pth_file="$1"; shift

  local pth_origin="$(cd -P -- "./$(git rev-parse --show-cdup)" && pwd -P)"
  if [[ ! -d "$pth_origin/.secrets/." ]]; then
    logger_fatal "could not find secrets in $pth_origin/.secrets"
    exit 1
  fi

  openssl enc -d -base64 -aes-256-ecb -kfile "$pth_origin/.secrets/pass" -in "$pth_file" 2> /dev/null || cat "$pth_file"
}

require sub "$BASH_SOURCE" "$@"
